### ISSUE TITLE
Failed to add mutation

### ISSUE THREAD

**Issue by olafmaurer** [stryker-mutator/stryker4s#1024]
### Summary

```
[warn] Failed to add mutation(s) 272 to new mutated code
[warn] The code that failed to mutate was: [{
[warn]       for {
[warn]         m1 <- m
[warn]         m2 <- otherMap
[warn]         union = m1 ++ m2
[warn]         if m1.size + m2.size == union.size
[warn]       } yield union
[warn]     }.catchSome {
[warn]       case _: NoSuchElementException => {
[warn]         Task.fail(new Throwable("Duplicates found"))
[warn]       }
[warn]     }.mapError(
[warn]       e => new Throwable(s"Error during concatenation while reading input", e)
[warn]     )] at Input.File(new File("[...].scala"), Charset.forName("UTF-8")):95:79
[warn] This mutation will likely show up as Survived
```
This is generic code to take two maps and make a union of them, failing if any keys are duplicated in a function with the signature `def concatAndVerifyDisjoint(otherMap: Task[Map[K, V]]): Task[Map[K, V]]` (using Task from ZIO)

### Stryker4s config

```
default config
```

### Stryker4s environment

```
stryker4s 0.14.1
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        |     2.13.6       |
| Build tool & version |     SBT 1.5.5       | 
| Operating System     |   Linux         |

**Comment by hugo-vrijswijk** [comment]
Fixed in 0.15.0 (finally! 😁)
