### ISSUE TITLE
Is it possible to run unit test cases that are related to certain source file instead of all test cases?

### ISSUE THREAD

**Issue by ayush9999-qa** [stryker-mutator/stryker4s#1047]
### Stryker4s config

```hocon
```

### Stryker4s environment

```
stryker4s x.x.x
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        |            |
| Build tool & version |            | 
| Operating System     |            |

**Comment by hugo-vrijswijk** [comment]
Hi, as of (0.14.1)[https://github.com/stryker-mutator/stryker4s/releases/tag/v0.14.1] the sbt plugin supports per-test coverage, which means it only runs the test that will hit a particular mutant, instead of all tests. Is this what you mean? I'll close this issue as answered, if not please reopen it 😄

**Comment by ayush9999-qa** [comment]
Yes I meant the same. Thank you @hugo-vrijswijk

**Comment by ayush9999-qa** [comment]
@hugo-vrijswijk , may I know how do stryker track/map what tests to run?

**Comment by hugo-vrijswijk** [comment]
@ayush9999-qa Of course! Stryker4s uses coverage mapping by keeping track of what code is hit during the initial test run. When running tests, we use test information provided by sbt to correlate that to the coverage info. You can read more about how sbt works with Stryker4s in our blog article: https://stryker-mutator.io/blog/stryker4s-40-minutes-to-40-seconds.

There's no super clear logging of what tests Stryker4s runs per mutant, but you could enable debug logging to view the messages between the main Stryker4s process and the testrunner, where the main process tells the testrunner what tests to run, that looks something like this:

```
[debug] Sending message StartTestRun(3,Vector(stryker4s.report.ConsoleReporterTest))
```

Where '3' is the mutant, and ConsoleReporterTest is the only test running for that mutant
