### ISSUE TITLE
Update mutators to new categories

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#108]
[See this issue in the handbook](https://github.com/stryker-mutator/stryker-handbook/issues/11). 

Categories would have to be changed in the `Mutator` traits, `Exclusions` strings, and in the supported mutators documentation.

We might also want to remove our own mutators documentation and link to the handbook instead, so there's only a single place to update for new mutators

**Comment by legopiraat** [comment]
Should we wait for this issue until the handbook is merged?

**Comment by hugo-vrijswijk** [comment]
The issue is now merged, so this can be picked up
