### ISSUE TITLE
Running initial test run doesn't copy JVM system settings

### ISSUE THREAD

**Issue by mthmulders** [stryker-mutator/stryker4s#119]
### Summary

Running initial test run doesn't copy JVM system settings.

My tests require a JVM system setting (`-Dconfig.file=...`) to point to a configuration file for the environment where the tests are ran. Running `sbt -Dconfig.file=... test` runs fine. Running `sbt -Dconfig.file=... "project app" stryker` (since I'm using a multi-module structure) fails with:

    [info] *** 4 SUITES ABORTED ***
    [info] *** 14 TESTS FAILED ***
    [error] Failed tests:
    [error] 	hyperion.MeterAgentSpec
    [error] 	hyperion.DailyHistoryActorSpec
    [error] 	hyperion.RecentHistoryActorSpec
    [error] Error during tests:
    [error] 	hyperion.database.DatabaseActorSpec
    [error] 	hyperion.AppSettingsSpec
    [error] 	hyperion.rest.AppInfoServiceSpec
    [error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
    [error] stryker4s.extensions.exceptions.InitialTestRunFailedException: Initial test run failed. Please make sure your tests pass before running Stryker4s.
    [error] stryker4s.extensions.exceptions.InitialTestRunFailedException: Initial test run failed. Please make sure your tests pass before running Stryker4s.
    [error] Use 'last' for the full log.

See [the build log](https://circleci.com/gh/mthmulders/hyperion/348) and [the source code repository](https://github.com/mthmulders/hyperion/tree/mutation-testing) for more details.

### Stryker config

```hocon
stryker4s {
  base-dir = "app"
  log-level = debug
  mutate = [
    "app/src/main/scala/**/*.scala"
  ]
  reporters = [
    console
  ]
}
```

### Stryker4s environment

```
stryker4s 0.1.0
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        | 2.12.8 |
| Build tool & version | SBT 1.2.8 | 
| Operating System     | MacOS Mojave (10.14.2) |

**Comment by hugo-vrijswijk** [comment]
I believe the Java properties setting doesn't apply to all those commands. Could you try playing around with the syntax or order a bit more (maybe add the property command as the second option). Adding something like `javaOptions in Test += "-Dconfig.file=..."` to your build.sbt should also work.

**Comment by mthmulders** [comment]
I believe the properties are in the right place, I already tried playing with the order and it gave failures not related to Stryker but to SBT itself.
The reason why they're not in build.sbt is that this config file varies over environments... There's different config files for the CI environment, my local machine, etc....

**Comment by hugo-vrijswijk** [comment]
Hmm, I see. I agree doing it via the CLI should be possible. I can't look at the project at the moment (cool project btw). I'll see if I can give it a try maybe tonight or tomorrow

**Comment by hugo-vrijswijk** [comment]
I've done a bit more research into this. The issue is that we fork the JVM for each test run, this means that any JVM properties are not added to the new JVM with the method used above. I couldn't find a way to properly set them. I did do a quick test with a custom build of stryker4s with the property hardcoded in. That worked, I saved the result [here](https://gist.github.com/hugo-vrijswijk/deec09f90fbc0d694b278f92b55f6678) to save you some time.

Thanks for reporting the issue! This is definitely something we should look into a bit more and find a proper fix for.

**Comment by mthmulders** [comment]
I'm very happy to see progress on this issue.

Unfortunately, looking at #136 I can't really see how to use this feature. It says it works with "a config option in stryker4s.conf" but the code changes don't tell me which one. The [configuration reference](https://github.com/stryker-mutator/stryker4s/blob/master/docs/CONFIGURATION.md) doesn't tell me either...

**Comment by mthmulders** [comment]
Yay for "just working". Looking forward to try it! I wouldn't know how to test the pre-release. Is that just cloning this repo and installing it in my local Maven repo? Would be happy to give it a shot before the release is out ;-)

**Comment by hugo-vrijswijk** [comment]
Even better, we now have fancy [snapshot builds](https://github.com/strykermutator/stryker4s#pre-release-versions). The badge doesn't work yet unfortunately but the last snapshot version is `0.1.0+19-8c5511eb-SNAPSHOT`. Use that as the version, and add the snapshot resolver to `plugins.sbt`

**Comment by mthmulders** [comment]
How awesome! I've got it running, thanks!
