### ISSUE TITLE
Fail run below mutation score threshold

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#12]
Add a configuration option to fail (exitcode 1) below a certain mutation score. Similar to [the scoverage minimum](https://github.com/scoverage/sbt-scoverage#minimum-coverage), or to the [Stryker threshold](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/README.md#thresholds-for-mutation-score)

**Comment by Wmaarts** [comment]
I'll have a go at this one.

**Comment by legopiraat** [comment]
Cool :)

**Comment by legopiraat** [comment]
Closed is implemented in #109
