### ISSUE TITLE
Re-organize project modules

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#120]
I think we should re-organize the submodule structure. Right now there's no real functional difference between the `util` and `core` packages. We could combine those two into one. And while we're at it create a new `command-runner` package that contains all code needed for the command-runner, so that's not needlessly added into packages that don't need it (like the sbt plugin).

This way we would end up with 3 packages:
- sbt-stryker4s
- stryker4s-core
- stryker4s-command-runner (or something similar)

**Comment by hugo-vrijswijk** [comment]
Haha, same. But that is what sbt recommends, so I think we should follow that. Maven has its own naming convention for plugins which we'll run into as well eventually

**Comment by legopiraat** [comment]
We could potentionally do something like `(project withId "sbt-stryker4s" in file("stryker4s-sbt"))` if we really wanted to.

**Comment by hugo-vrijswijk** [comment]
The folder and module names are already different though. ```scala
project withId "sbt-stryker4s" in file("sbt")
```

**Comment by legopiraat** [comment]
Which could also be re-organized :D

**Comment by legopiraat** [comment]
@hugo-vrijswijk I just made a small proposal for the new structure in the build.sbt file:
https://github.com/stryker-mutator/stryker4s/blob/re-organize-project-modules/build.sbt

Will this suffice? In my opinion, it will work nicely as far as I can see.

**Comment by hugo-vrijswijk** [comment]
Yeah, looks good to me. Is the `runners` project necessary though for the subfolder? If so, we should also pay attention not to publish it (like is done with the root project)

**Comment by legopiraat** [comment]
Yes I was thinking about that as well after I pushed it, I wrote it down so I won't forget to check 👍
