### ISSUE TITLE
Deleted git file still tries to be copied over

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#133]
If a file is deleted from git, but not staged, it still shows up in the `git ls-files --others --exclude-standard --cached` command we run to gather files that should be copied over. This causes a `FileNotFoundException` when running Stryker4s

How to reproduce:

1. Delete a file from git (e.g. stryker4s.conf)
2. Run `git ls-files", "--others --exclude-standard --cached | grep 'stryker4s.conf'`, the file shows up
3. Run `git add stryker4s.conf`
4. Run the command from step 2 again, the file no longer shows up

**Comment by nicojs** [comment]
This is something we ran into with Stryker as well 🙈 . Didn't know you guys were using the same `git ls-files` command. 

We're filtering files that do not exist using our implementation of readFile: 

https://github.com/stryker-mutator/stryker/blob/66d65f76dae8bf0fab050d22609a095acb0ba9e7/packages/stryker/src/input/InputFileResolver.ts#L170-L189

**Comment by hugo-vrijswijk** [comment]
Ha. I actually took a look at what you guys were doing while working on a fix (#134) and fixed it the same way. Thanks!
