### ISSUE TITLE
Compile error for class with custom `min` method

### ISSUE THREAD

**Issue by lionralfs** [stryker-mutator/stryker4s#1412]
### Summary

I'm using a class which has a custom `min` method. A call to this method is mutated to `max` (which doesn't compile). Here's a simplified example:

```scala
package example

object Hello extends App {
  val a = TestClass(1)
  val b = TestClass(2)

  val result = a.min(b)
}

case class TestClass(value: Int) {
  def min(other: TestClass): TestClass = if (other.value < value) other else this
}
```
↓↓↓
```
[error] [...]/target/stryker4s-14048246708735125125/src/main/scala/example/Hello.scala:7:9: value max is not a member of example.TestClass
[error]       a.max(b)
[error]         ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

I'm noticing the same behavior for other classes with methods like `filter`, `nonEmpty` etc.

### Stryker4s config

```hocon
none (default)
```

### Stryker4s environment

```
stryker4s 0.14.3
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        | 2.13.11           |
| Build tool & version |  sbt 1.9.4         | 
| Operating System     | macOS 13.5.2           |

**Comment by hugo-vrijswijk** [comment]
Hi, thanks for opening the issue. There should be an attempt to rollback the compile error. Could you share some more of the logs where this might (not) be happening?

**Comment by lionralfs** [comment]
When using sbt, there is a rollback attempt, correct. With gradle, for example (through the `test-runner` config), there isn't. Is that a known limitation because you can't know whether the compilation or the test itself failed?

**Comment by hugo-vrijswijk** [comment]
Yes, (currently) only sbt has support for rollback. Maven could have it (but no timeline, unfortunately), and a potential gradle plugin could too. But the test-runner can never support it for the reason you mentioned

**Comment by lionralfs** [comment]
Ok thanks for the explanation. Ideally, the mutation is not created in the first place. Is that feasable?

**Comment by hugo-vrijswijk** [comment]
You can exclude a mutation by adding [a `@SuppressWarnings` annotation](https://stryker-mutator.io/docs/stryker4s/configuration/#excluding-specific-mutations) above the code (that calls the `.min`, not the `def min`). Or exclude the entire category

**Comment by lionralfs** [comment]
Yeah that's what I'm currently doing. The annotation unfortunately also excludes other mutations of the same type which would be cool to keep. I was hoping that there could be a better way. I'm unfamiliar with the library internals but I was thinking about adding a check to ensure that `def max` exists, for example.

**Comment by hugo-vrijswijk** [comment]
🥫🐛 Stryker4s actually doesn't have any type-information at all when mutating your code. So it doesn't know if the `min` also has a `max`. There's two paths around this, one of them is rollback, the other is getting type-information about your code. This _might_ be possible with SemanticDB or Tasty (Scala 3), but I haven't had the time to fully look into it. I'll close this issue for now
