### ISSUE TITLE
Initial test run

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#15]
Run an initial test run without any mutations active so we can ensure the application runs. Could also be used to collect code coverage data for #13

**Comment by legopiraat** [comment]
Would be nice if we could make the initial run async as well. 

So do a test run and search + mutate in the background. But then lets wait for the initial testrun to finish before we fire up the rest.

**Comment by hugo-vrijswijk** [comment]
Not sure if that's the best approach. If we run the tests on the mutated version of the application (but without any activated mutants) we can later use that for code coverage analysis and compile error checking

**Comment by hugo-vrijswijk** [comment]
Already implemented, see [MutantRunner](https://github.com/stryker-mutator/stryker4s/blob/e5c15b42839d3f8320eb7bdc3b83874b34bef808/core/src/main/scala/stryker4s/run/MutantRunner.scala#L92)
