### ISSUE TITLE
Log killed mutants in report

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#156]
It'd be nice to also see the killed mutants, possibly with a config option.

Configuration would be something like this:

```conf
stryker4s {
  reporters: [
    console: {
      log-killed-mutants: true
    }
  ]
}
```

Default would be false? Not sure what is best here

We should also still support the old configuration: `reporters: [ "console" ]`

**Comment by legopiraat** [comment]
Your confusing me with this issue title and description ;)

the title says you want to log killed mutants and in your first sentence you say its nice to log survived mutants. So what is it you want to log? since we already the survived mutants i suppose?

**Comment by hugo-vrijswijk** [comment]
Oops, yeah that should say killed mutants. 

Alternatively to a config setting, we could log survived mutants to debug, similar to Stryker

**Comment by legopiraat** [comment]
So how do envision we log these mutants?

```
// Killed
Killed: original `list.filter(_ > 1)` mutated `list.filterNot(_ > 1)`

// Survived
Survived original `list.filter(_ > 1)` mutated `list.filterNot(_ > 1)`
```
Something like that or something completely different?

And maybe a suggestion for the config key would be `strykers.extended-mutation-logging = true`
Or make a fully different logger that does this by default instead of adding another config key?

Something like the `extendedConsoleLogger` (yes it's a terrible name)

**Comment by marcindulak** [comment]
How is this information available? Can we have it in a diff format?

**Comment by hugo-vrijswijk** [comment]
What do you mean with a diff format?

**Comment by marcindulak** [comment]
I'm thinking about the format - can we have this information logged as https://en.wikipedia.org/wiki/Diff?

**Comment by Wmaarts** [comment]
[Since the question is slightly off-topic for this issue I responded on Gitter. ](https://gitter.im/stryker-mutator/stryker4s?at=5c656fc1dc3f0523ccb46a83)

**Comment by nicojs** [comment]
A relatively easy solution might be to log the survived mutants on debug. I wouldn't spend too much time on this feature because in my experience people care less when the HTML reporter is there
