### ISSUE TITLE
Invalid code generated for (!_.foo("bar"))

### ISSUE THREAD

**Issue by RCMartins** [stryker-mutator/stryker4s#161]
### Summary

Here is minimisation of the issue:

```scala
object Main {
  def main(args: Array[String]): Unit = {
    List(1, 2, 3).map(!_.toString.startsWith("1"))
  }
}
```

becomes:

```scala
object Main {
  def main(args: Array[String]): Unit = {
    List(1, 2, 3).map(!(sys.props.get("ACTIVE_MUTATION") match {
      case Some("1") =>
        _.toString.startsWith("")
      case _ =>
        _.toString.startsWith("1")
    }))
  }
}
```

```
with two compiler errors:
missing parameter type for expanded function ((x$1: <error>) => x$1.toString.startsWith(""))
[error]         _.toString.startsWith("")
[error]         ^
missing parameter type for expanded function ((x$2: <error>) => x$2.toString.startsWith("1"))
[error]         _.toString.startsWith("1")
[error]         ^
```

This problem probably happens in other cases.
This could be solved by placing the 'ACTIVE_MUTATION' block just around the string like:
```scala
object Main {
  def main(args: Array[String]): Unit = {
    List(1, 2, 3).map(!_.toString.startsWith((sys.props.get("ACTIVE_MUTATION") match {
      case Some("1") =>
        ""
      case _ =>
        "1"
    })))
  }
}
```

### Stryker4s config

default

### Stryker4s environment

```
stryker4s 0.2.1
```

### Your Environment
| software                    | version(s) |
| -------------------- | ---------- |
| Scala version            |  2.12.8          |
| Build tool & version  | SBT 1.2.8          | 
| Operating System    | MacOS Mojave 10.14.3           |

**Comment by hugo-vrijswijk** [comment]
Thank you for the bug report! I'll have a look at fixing this now. 

>  This could be solved by placing the 'ACTIVE_MUTATION' block just around the string like:

I think it's a good idea to place the 'ACTIVE_MUTATION' block only around literals, where it is always possible. But I don't think that would fully fix the issue. For example, pretty sure that in `listOfLists.map(_.filterNot(func)` the statement would be around `_.filterNot(func)`, which would also break.
