### ISSUE TITLE
Invalid code generated for case classes with implicit params

### ISSUE THREAD

**Issue by RCMartins** [stryker-mutator/stryker4s#162]
### Summary

The code mutated changes original Class parameter modifiers.
It moves the `implicit` keyword to the beginning of the parameter list, making all the parameters implicit, instead of just the correct parameter.

Here just the `string1` is implicit:
```scala
class class1(
    number1: Int,
    implicit val string1: String = "default"
)
```

---

In the mutator code both `number1` and `string1` become implicit:
```scala
class class1(implicit number1: Int, val string1: String = sys.props.get("ACTIVE_MUTATION") match {
  case Some("1") => ""
  case _ => "default"
})
```

### Stryker4s config

default

### Stryker4s environment

```
stryker4s 0.2.1
```

### Your Environment
| software                    | version(s) |
| -------------------- | ---------- |
| Scala version            |  2.12.8          |
| Build tool & version  | SBT 1.2.8          | 
| Operating System    | MacOS Mojave 10.14.3           |

**Comment by hugo-vrijswijk** [comment]
Wow, that is a pretty crazy result! This seems to be a bug in Scalameta, though. 

When I run the following:

```scala
val tree = q"class foo(number1: Int, implicit val number2: Int = 4)"
tree.syntax == "class foo(number1: Int, implicit val number2: Int = 4)" // false
tree.syntax == "class foo(implicit number1: Int, val number2: Int = 4)" // true
```

Not sure if we can really make a workaround for this. I'll make an issue in Scalameta

**Comment by hugo-vrijswijk** [comment]
A workaround you could do if you run into this problem would be to change the signature of the class to `class class1(number1: Int)(implicit val string1: String = "default")`. I know this isn't ideal, but it should keep source code calling the class the same.
