### ISSUE TITLE
Stryker4s-CLI

### ISSUE THREAD

**Issue by legopiraat** [stryker-mutator/stryker4s#21]
Currently we don't have support for a build tool but also build tools in Scala is a hot topic. 

There are tons of build tools out there and we will not be able to support and maintain them all. 
A common CLI tool would be a good way to provide mutation testing for people using other build tools.

What are your thoughts on this @hugo-vrijswijk ?

**Comment by hugo-vrijswijk** [comment]
How would you see the CLI be distributed/used? As a .jar that people can then call, or more similar to the [current Stryker-cli](https://github.com/stryker-mutator/stryker-cli)?

I imagine we wouldn't be able to support more than the current process-runner for it. Maybe we could refactor that to make it more generic (support for more CLI-commands, shouldn't be hard) and add a CLI to it.

**Comment by legopiraat** [comment]
Yes i think we would distribute this as a jar. 

Possible commands could be

- start <-- Do a full mutation test run
- dryRun <-- Run tests without mutations + search all mutations and compile the code.
- configFileLocation <-- Override the config file location.
- logLevel <-- Change the current logLevel 
- help <-- To see all available commands

This could be a set of commands we could provide for example

**Comment by hugo-vrijswijk** [comment]
I also think most (or all) config options should be available through the CLI, that would make it easier to quickly test out changes in config

**Comment by nicojs** [comment]
I agree. I don't see value in the commands `configFileLocation` and `logLevel`. Those should be _options_ rather than _commands_ IMHO.

I would rename `start` to `run` to keep it in line with Stryker

**Comment by legopiraat** [comment]
Well that depends if we want to keep inline with the Stryker-CLI or with our sbt/maven plugin style. Because if we choice `run` in the CLI that would conflict with `sbt` for example. We should think carefully on which part we want to align.

**Comment by hugo-vrijswijk** [comment]
Having a `configFileLocation` option in the CLI could be useful when the user wants different configurations for e.g. build server or local development, or testing different scenario's

**Comment by legopiraat** [comment]
What Nico means is this case:

```
run -configLocation="some/location/stryker4s.conf"
```

**Comment by hugo-vrijswijk** [comment]
Yes. So on the build-server you could run `run --config stryker4sbuildserver.conf` while local it would be `run --config stryker4slocal.conf` or `run --config stryker4sWithTemporarySpecialOptions.conf`.

**Comment by hugo-vrijswijk** [comment]
As this is likely far in the future for us, or maybe out of scope. Here's a wild idea: it would be pretty cool to be able to use the [stryker-cli](https://github.com/stryker-mutator/stryker-cli) for all versions of Stryker (JS, .NET and Scala). Would probably require a major rewrite and a lot of work, but it seems pretty cool. Even if only for adding Stryker to a project and starting the correct run command. @nicojs @richardwerkman thoughts?

**Comment by nicojs** [comment]
Yeah I've been thinking about that as well. The only downside is that you would need to install NodeJS. You think that is a big problem?

**Comment by richardwerkman** [comment]
@hugo-vrijswijk Honestly I don't see the added value in that. From the perspective of a .NET user it would be unlogical to need to install Stryker using NPM. I would expect to install Stryker using nuget or maybe download a executable. The only plus point I can think of is that we can share the logic for the HTML report on all versions. Stryker-cli would execute one version of stryker and expects a json file as output and starts the html report using that file. But this is not that big of a feature that we would save much work for ourselves. But if you can tell me why we should do this I'm open to the idea!

**Comment by hugo-vrijswijk** [comment]
Closing this issue as it doesn't seem likely this will be done in the near future, or provide much extra value for us over build-tool plugins.
