### ISSUE TITLE
Add stryker4s dashboard badge

### ISSUE THREAD

**Issue by legopiraat** [stryker-mutator/stryker4s#215]
Since we now have an stryker dashboard reporter it would be nice if Stryker4s uses this to report it's own score on the readme.

Should be done by one of the maintainers since we need to generate an api key which is repo based.

**Comment by hugo-vrijswijk** [comment]
We could run stryker4s as a CRON job nightly. Unfortunately I think we can only run on `core` as we have no good way of dealing with multiple modules yet

**Comment by hugo-vrijswijk** [comment]
Closed by #320: [![Mutation testing badge](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fbadge-api.stryker-mutator.io%2Fgithub.com%2Fstryker-mutator%2Fstryker4s%2Fmaster)](https://dashboard.stryker-mutator.io/reports/github.com/stryker-mutator/stryker4s/master)

Mutation testing is run on core, maven-plugin and command-runner. The report is available [here](https://dashboard.stryker-mutator.io/reports/github.com/stryker-mutator/stryker4s/master) (or by clicking on the badge). Each module also has a readme with the badge
