### ISSUE TITLE
Call reporters asynchronously

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#234]
Right now each reporter is called in order. There's no real reason for this. The process could be sped up by calling each asynchronously and waiting until they are all finished before continuing. 

Questions I still have:
- What about progress reports? Should those be async as well? And should the mutation run wait for all reporters, or should the reporter be fully async, so the runner will continue without waiting. 
- Implementation? We could use Scala futures, but this might be a good entry-point into Cats-effect if we want to go in that direction

**Comment by scubamaggo** [comment]
Has there been any more considerations regarding Future vs IO (cats-effect)? It looks like the former should be relatively trivial while the latter would at the very least need some consideration how much of the code base should be switched to IO.

**Comment by hugo-vrijswijk** [comment]
At this point I think the direction of cats-effect is too substantial for this project. There's also the point of a higher learning curve for new contributors with IO. The best way to go is probably Future-based by having each reporter return a `Future[Unit]` and joining them.
