### ISSUE TITLE
Sys variable used in bytecode, creates conflict with sys variable used in project code

### ISSUE THREAD

**Issue by MiguelLiraLuis** [stryker-mutator/stryker4s#238]
### Summary
When I run for the first time Stryker4s in my project, I found an error related with sys variable used in ```sys,env.get("ACTIVE_MUTATION")```. I have a sys variable in my code, and when I run the framework, this create an error.
To resolve this I change the sys variable in my code to sys2, and then the framework works perfectly.

### Stryker4s config

```hocon
Default configurations.
```

### Stryker4s environment

```
stryker4s 0.5.0
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        |      2.13.0      |
| Build tool & version |     Maven 3.6.0       | 
| Operating System     |  macOS Mojave          |

**Comment by hugo-vrijswijk** [comment]
Thanks for creating this issue! This is definitely a case of "huh, didn't think of that, but it makes sense". The `sys` variable we use comes from the `scala.sys` package, but is already imported automatically. I wonder if changing the variable to `scala.sys.env.get....` would fix this

**Comment by dwestheide** [comment]
> Thanks for creating this issue! This is definitely a case of "huh, didn't think of that, but it makes sense". The `sys` variable we use comes from the `scala.sys` package, but is already imported automatically. I wonder if changing the variable to `scala.sys.env.get....` would fix this

Probably, it would be best to replace any `sys` in generated code with `_root_.scala.sys` to be on the safe side. Even `scala.sys` could clash with user's code, even though chances are not very high.

**Comment by MiguelLiraLuis** [comment]
Yeah, I agree with changing any variable sys in the generated code, because sys is a variable very used in the code for many projects, but if this doesn't fix the error, it's better if you create a note though to warning people.
