### ISSUE TITLE
Tests for logging

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#26]
It'd be nice to have a way to test logged statements as they are shown to the user. Mixing in the Logging trait like we do now makes it hard to capture logs or mock the logger. From what I can tell, there are a couple of ways to capture logging:

- Inject the logger in the constructor and mock it away in tests. Maybe even with a default constructor like `class Foo(logger: Logger = LogFactory.getLogger())` so it doesn't require a lot of extra code in the application. Downside to this is it's not as clean as adding a trait, and (I think) can't be used on objects. Not the biggest problems.
- Capture Logback output using a custom Logback appender. Similar to [Log4s](https://github.com/Log4s/log4s#log4s-testing). I'm not very familiar with Logback, so this could be a bit of work. 
- Capturing stdout

Logged statements should be able to be filtered on the right class. And shouldn't get confused when tests are ran multithreaded (not sure how 2 & 3 would work with this).

**Comment by nicojs** [comment]
I would prefer the second way of working. That way, you can keep mixing in the `Logging` trait like you do now (kind of the scala way of doing things). The problem with capturing the stdout is that is difficult to do and it would break if you decide to log to a file in the future. 

I've used slf4j test in the past for both Java and Scala projects. Worked well enough. http://projects.lidalia.org.uk/slf4j-test/

**Comment by hugo-vrijswijk** [comment]
I've created a work-in-progress on the [branch logging-tests](https://github.com/stryker-mutator/stryker4s/tree/logging-tests). SLF4J-Test seems to work well, but right now is conflicting with the logback SLF4J implementation on the classpath. I was running into some issues with excluding it only when in test projects.

**Comment by legopiraat** [comment]
I think you should be able to create a second logback.xml file which is a test resource. That would solve the issues you have i think? (not sure what issues you have)

**Comment by hugo-vrijswijk** [comment]
The issue I'm having is both the SLF4J-Test and Logback-classic provide SLF4J bindings. This causes a conflict, and the JVM will decide a binding basically at random. This means the logging tests work half the time which is obviously not exactly ideal. SLF4J logs the following warning:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/hugod/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/hugod/.ivy2/cache/uk.org.lidalia/slf4j-test/jars/slf4j-test-1.2.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

So what we want is to exclude the logback binding in tests. SLF4J-Test also [mentions this and provides a Maven example](http://projects.lidalia.org.uk/slf4j-test/index.html#Setting_up). I've tried setting it up in SBT using 
```scala
excludeDependencies in Test += "ch.qos.logback" % "logback-classic"
```
But SBT seems to ignore it when specifying `in Test`. It works when excluding it in the whole project but we don't want that, of course.

Maybe someone with a bit more SBT experience could chime in. @legopiraat ?
