### ISSUE TITLE
Comply with the new HTML reporter specification

### ISSUE THREAD

**Issue by legopiraat** [stryker-mutator/stryker4s#29]
Things that need to be done to comply with new HTML reporter specification so we can integrate with it smoothly.

- [ ] Change internal structure of `MutantRunResults` and `MutantRunResult` to the new report data. 
- [ ] Calculate the span of the mutation.
- [ ] Collect information about mutations per file.
- [ ] Calculate `health`

Followup on this will be to integrate the new html reporter.

**Comment by legopiraat** [comment]
This change seems to have a fairly big impact on the code. Also with several ways to go maybe we should have a discussion on which way we want to go for this change @hugo-vrijswijk.

**Comment by hugo-vrijswijk** [comment]
If it is too much changes in the current codebase, we could always make a mapper or something to leave the current codebase intact. But I think it should be possible

Regarding the mutations per file, that shouldn't be too much work. Right now all mutations are already collected per file, but are then flatmapped when running them. 

The health seems related to # . We could hard-code the health percentages. Though I don't think just implementing health information and a  config without 'breaking' the build on a lower score would be too big of a feature to implement first.

Why did you already check off the span point? Maybe we should do individual PR's for each point. To keep them small.

**Comment by legopiraat** [comment]
At this point i think a mapper is the way to go for now. And in the future work towards a more maintable solution.

**Comment by nicojs** [comment]
Is there any progress on this? There is a [`0.0.4` version of the mutation testing elements](https://github.com/stryker-mutator/mutation-testing-elements/issues/2#issuecomment-464881050). It would be awesome to have an example of a Scala report to test the with.

**Comment by hugo-vrijswijk** [comment]
Yes! I've started working on it again in the `[Comply-html-reporter-format](https://github.com/stryker-mutator/stryker4s/tree/Comply-html-reporter-format)` branch. Believe me, we are just as excited to have something to test with 😀
