### ISSUE TITLE
[Dashboard] Support GitHub actions

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#307]
We should support GitHub actions for uploading reports to the stryker dashboard. 

Thankfully, Stryker already supports it, so we can copy the needed environment variables from there: https://github.com/stryker-mutator/stryker/blob/master/packages/core/src/reporters/ci/GithubActionsProvider.ts

**Comment by rrsai** [comment]
I'd like to implement Stryker with github actions, is there any example repo of that being done that I could learn from?

**Comment by hugo-vrijswijk** [comment]
@rrsai Yes! Stryker4s itself uses GitHub actions to run mutation testing on the master branch and upload to the dashboard. You can see the action [here](https://github.com/stryker-mutator/stryker4s/blob/master/.github/workflows/mutation-testing.yml). There's a bit more setup involved because stryker4s is a multi-module project
