### ISSUE TITLE
Feature proposal: time-out detection

### ISSUE THREAD

**Issue by mthmulders** [stryker-mutator/stryker4s#312]
Due to mutated Scala code, it is possible that the code under test contains an endless loop. Right now, Stryker4s would just wait for the test to finish.

My suggestion is to build a timeout detection (just like [Stryker for Javascript has](https://github.com/stryker-mutator/stryker/tree/master/packages/core#timeoutMS)). It should detect that the test runs way too long, and then change the mutant status to "TimedOut" or something like that.

I'd love to play around and see if I can build it, but I have very limited time at this moment. Let's keep this issue for discussing whether this is needed, and how it should work.

**Comment by hugo-vrijswijk** [comment]
Closed in #573
