### ISSUE TITLE
Formatting discussion

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#34]

**Comment by hugo-vrijswijk** [comment]
We already have a `.scalafmt.conf` file in the project. But we have no rules on when (or if) to apply them. In my opinion, the defaults that Scalafmt has are already quite good. 

We could add a build step in Travis that breaks the build on non-formatted code with `sbt scalafmtCheck`

**Comment by legopiraat** [comment]
With the new intellij version (18.2) there was something about overriding intellij default formatting to the `.fmt` file. Then we could automaticlly format the file using [SaveActions](https://plugins.jetbrains.com/plugin/7642-save-actions)

**Comment by legopiraat** [comment]
The defaults look fine, i would just like to have a longer line length but that personal i guess?

**Comment by hugo-vrijswijk** [comment]
I agree. I added the line length as a 'reason' to keep lines short, but in the end it ends up just producing ugly lines like these:

https://github.com/stryker-mutator/stryker4s/blob/e77da643cc2fde2879c4ef53e82f34e4f829c7b3/core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala#L331-L332

So I'm fine with changing it to something like 120?

**Comment by hugo-vrijswijk** [comment]
We should probably wait until [Scalafmt v1.6.0](https://github.com/scalameta/scalafmt/milestone/24) is released, to prevent having to format the entire codebase again then

**Comment by legopiraat** [comment]
Since Scalafmt 1.6.0 still isn't out yet I don't feel like waiting on it anymore at the moment. I'll have a go at this now.

**Comment by hugo-vrijswijk** [comment]
Funny you mention that today. It looks like commit activity is picking up a bit again on scalafmt (as of today).
