### ISSUE TITLE
Configurable ProcessRunner

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#36]
We should make the ProcessRunner configurable for multiple test commands, instead of a hardcoded `sbt test`. This means we, in principle would, support gradle and maven. 

When in the future we have 'proper' support for a build tool (like SBT in #2 ) we could show a warning when a user runs with the 'slower' process runner.

**Comment by mdbergmann** [comment]
Out of curiosity. We have a Gradle project. Can I run stryker4s on a Gradle project?

**Comment by hugo-vrijswijk** [comment]
@mdbergmann You can use the [command-runner](https://stryker-mutator.io/docs/stryker4s/configuration#process-runner-config) to run Gradle projects, but you won't get great performance. We don't have an official plugin for easier use or better performance (yet). If this is something you need, feel free to open an issue or PR!

`stryker4s.conf`

```conf
stryker4s {
  test-runner: { command: "./gradlew", args: "test" }
  mutate: [ "app/src/main/**/*.scala" ]
}
```

The fastest way to launch the command-runner is probably with [Coursier](https://get-coursier.io/docs/cli-launch):

```sh
$ cs launch io.stryker-mutator::stryker4s-command-runner:0.11.0
```

**Comment by mdbergmann** [comment]
OK, many thanks.
This should be good enough for me.

**Comment by mdbergmann** [comment]
Hmm. It seems the config key 'test-runner' is not known anymore:

11:20:33.524 WARN  Stryker4s: The following configuration key(s) are not used, they could stem from an older stryker4s version: 'test-runner, log-level'.

Any idea?

**Comment by hugo-vrijswijk** [comment]
I think this is a bug in the command runner. It's a required value for the command-runner, so should be picked up (otherwise Stryker4s would error)
