### ISSUE TITLE
Configurable reporter

### ISSUE THREAD

**Issue by legopiraat** [stryker-mutator/stryker4s#37]
Ability to configure which reporter(s) should be used after the mutation test run is completed.

I think one or more reporters will be a nice addition.
Shouldn't be hard to implement but on the console you will see a quick mutation score with a duration. And the actual html reporter would contain detailed information.

Merge into: `HTML-Reporter`

**Comment by hugo-vrijswijk** [comment]
Good idea. We should keep the configuration similar to Stryker's reporter configuration. (Just an array with reporters)

**Comment by legopiraat** [comment]
Should be called `reporters` as of this open issue in Stryker https://github.com/stryker-mutator/stryker/issues/793
