### ISSUE TITLE
Case class to hocon string format

### ISSUE THREAD

**Issue by legopiraat** [stryker-mutator/stryker4s#39]
Currently, for all the configuration classes we need to implement our own `toString` method to print it nicely in `Hocon`. This is quite an error-prone process when a new field is added or renamed the `toString` needs to be edited aswell. 

We would love a generic way to change case classes to a `Hocon` String.

**Comment by hugo-vrijswijk** [comment]
I agree. The current way is quite error-prone and more work than it should be

**Comment by legopiraat** [comment]
Basically what we could do is convert it to JSON and then remove all the `"` because they are optional in `Hocon`. But somehow this also doesn't feel much better.

**Comment by hugo-vrijswijk** [comment]
I can't find an easy way to directly serialize a simple case class to a HOCON string. 

I did find two options, neither of which I really like. The first is to serialize to JSON, and parse that as a Typesafe Config object, then render that as a HOCON string. The second is to map the Config object back to a Typesafe config (with each value mapped manually). Which also doesn't seem ideal.

**Comment by legopiraat** [comment]
The first option at least seems automated, the second option would not be ideal no.

I've found some "pretty print" piece of code with some small alters I could get it close to the HOCON format but not quite the same.

**Comment by legopiraat** [comment]
Already fixed in #38
