### ISSUE TITLE
Mutants in pattern match always Survive when topStatement has a mutation

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#467]
In the following code block:

![image](https://user-images.githubusercontent.com/10114577/82488158-be575380-9adf-11ea-9399-89a7ad7fd2ab.png)

All mutants in the pattern match Survive, even though at least 1 test will fail when the code is changed to the suggested mutation. Only occurs when the topStatement before the pattern match has a mutation

[Reproduction repo here](https://github.com/hugo-vrijswijk/no-mutations-example)

Code is mutated to:

```scala
(_root_.scala.sys.props.get("ACTIVE_MUTATION") match {
      case Some("1") =>
        peopleToGreet.filter(_ == iceKing).size
      case Some("2") =>
        peopleToGreet.filterNot(_ != iceKing).size
      case _ =>
        peopleToGreet.filterNot(_ == iceKing).size
    }) match {
      case 1 =>
        s"Hello!"
      case 0 =>
        "No one to greet :("
      case _ =>
        "What a crowd!"
    }
```

For some reason the mutation inside the pattern match are filtered out

**Comment by nicojs** [comment]
Great catch. So apparently the mutant placer places the mutant incorrectly?
