### ISSUE TITLE
Why the heap gets filled so fast?

### ISSUE THREAD

**Issue by ag91** [stryker-mutator/stryker4s#497]
### Summary

I am very happy you are providing a port for Scala! It seems there is a memory leak, and I could not see a discussion about it: so I thought to start one.

I have just run this on an medium sized project with `JAVA_OPTS="-Xms512m -Xmx12g " sbt stryker`, 
and this is the state of the heap when it got to 40% of the test execution:

![strykerStats40%jpg](https://user-images.githubusercontent.com/6580039/84416358-6611fe00-ac14-11ea-9d6b-3e5d10925f98.jpg)

Now I guess you are running the test executions in parallel, but why they are not releasing resources?
Any chance you could give a high level design of the test execution, so I could give a look into diagnose which bit of the codebase most likely is stealing resources?
I would be happy to make this more usable for big projects.

### Stryker4s config

```hocon
stryker4s {
  mutate: [ "domain/src/main/scala/**/*.scala" ]
  test-filter: [ "xxx.yyyy.*" ]
  excluded-mutations: [
    "EqualityOperator",
    # "BooleanLiteral",
    # "ConditionalExpression",
    # "LogicalOperator",
    # "StringLiteral",
    # "MethodExpression"
  ]
}

```

### Stryker4s environment

```
stryker4s 0.8.1
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        |   2.12.10         |
| Build tool & version |   sbt         | 
| Operating System     |   Ubuntu 20.04         |

**Comment by hugo-vrijswijk** [comment]
Thank you for the detailed look into memory usage! Test runs are done synchronously (whether the tests per run are asynchronous depends on the user's sbt setup). We're currently [changing the way we run tests](https://github.com/stryker-mutator/stryker4s/pull/492), and this is one of the issues it will likely fix.

Before (so, currently), for each test we would [call the sbt `executeTests` task](https://github.com/stryker-mutator/stryker4s/blob/master/sbt/src/main/scala/stryker4s/sbt/runner/SbtMutantRunner.scala#L110). This is very similar to calling `test` in the sbt console. We also set `fork := true` to further reduce memory increase (and reduce performance). The issue _likely_ lies with sbt, as it is a [known thing](https://github.com/stryker-mutator/stryker4s#memory-usage) for memory to increase if you continually run `test` in a sbt console.

With the linked WIP PR tests will be run in a separate process, and without any sbt steps in-between. That means that:
1. If the memory starts getting crazy, we can just kill the process and start a new test-runner (this is what stryker.js already does)
2. No sbt code is called, so wherever a memory leak is in sbt (if there is one and it's not with us) it will be avoided

**Comment by ag91** [comment]
Ah very cool! Thanks for your explanation Hugo, I learned also something more about sbt.
I may wait for the PR to be merged in, try again and upload the maybe-improved analysis here.
If you find it valuable and I forget, please ping me :)

**Comment by hugo-vrijswijk** [comment]
@ag91 Hi! I have just [published the release](https://github.com/stryker-mutator/stryker4s/releases/tag/v0.10.0-RC1) I was talking about **(checks calendar)** a small 3 months ago! It starts a new dedicated java process for running tests which is not only a lot faster but should also keep the memory usage (of the main and child process) in check a little. Please test it out!

**Comment by ag91** [comment]
Well it ran too fast for any metrics! Well done @hugo-vrijswijk ! I think we can close this :+1:

**Comment by hugo-vrijswijk** [comment]
That is awesome to hear and certainly a good way to fix leaks 😁
