### ISSUE TITLE
Publish stryker4s on SonaType

### ISSUE THREAD

**Issue by philippw** [stryker-mutator/stryker4s#52]
[ScalaDex](https://index.scala-lang.org/) is to Scala, what npm is to Node/JavaScript: one canonical way of publishing, distributing and *finding* Scala projects.

We should claim our spot there and profit from their "looking for a contributor" and "recently released" features. This may help our exposure within the Scala community.

**Comment by legopiraat** [comment]
@hugo-vrijswijk Do we have a preference for ScalaDex or SonaType (Maven central)? We also could do both.

**Comment by legopiraat** [comment]
This also requires us to make some secrets available in travis so we can publish after build.

**Comment by legopiraat** [comment]
More references:
https://www.scala-sbt.org/1.x/docs/Publishing.html

**Comment by legopiraat** [comment]
@legopiraat @hugo-vrijswijk Reminder:

We need to test if we need to publish the `core` and `util` module as well.

**Comment by hugo-vrijswijk** [comment]
Perhaps we should also combine the `core` and `util` module into just `core`. There's no clear divide between the two
