### ISSUE TITLE
Filter out blocklisted Scala compiler options for Maven plugin

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#541]
Generated mutated code can cause certain compiler options to warn (unused variables, etc). This combined with `fatal-warnings` can cause compile errors after mutating code. In the sbt plugin, [those options are known](https://github.com/stryker-mutator/stryker4s/blob/master/sbt/src/main/scala/stryker4s/sbt/runner/SbtMutantRunner.scala#L24-L33) and [filtered out](https://github.com/stryker-mutator/stryker4s/blob/master/sbt/src/main/scala/stryker4s/sbt/runner/SbtMutantRunner.scala#L54) when Stryker4s runs. 

The same should be done for the Maven plugin to prevent the same issues.

For Maven, to start tests in Stryker4s the maven invoker plugin is used by building a [request](https://github.com/stryker-mutator/stryker4s/blob/master/maven/src/main/scala/stryker4s/maven/runner/MavenMutantRunner.scala#L52-L57) and [starting it](https://github.com/stryker-mutator/stryker4s/blob/master/maven/src/main/scala/stryker4s/maven/runner/MavenMutantRunner.scala#L36). The fix is probably in this area, but I am not familiar enough with how compiler options work in the Scala Maven plugin to provide more information.

**Comment by jozic** [comment]
I've found a way to setup profiles for the run, on line code change in the plugin itself and configuration on the call side

```xml
                    <plugin>
                        <groupId>io.stryker-mutator</groupId>
                        <artifactId>stryker4s-maven-plugin</artifactId>
                        <version>0.9.1-my-SNAPSHOT</version>
                        <configuration>
                            <project>
                                <activeProfiles>
                                    <profile>
                                        <id>stryker4s</id>
                                    </profile>
                                </activeProfiles>
                            </project>
                        </configuration>
                    </plugin>
```

ideally i want to find a way to pass command line arguments to the run, so that i can enable profiles or set other system properties (e.g. `-P stryker -Dprop=value`)
but this also helps, as at least this activates a profile and one can set a lot in a maven profile

@hugo-vrijswijk  would you be interested in PR for this profile propagation?

**Comment by hugo-vrijswijk** [comment]
@jozic Both options should work 'out of the box' in my opinion, so PR's are definitely welcome! The Maven plugin can use some love 🤗
