### ISSUE TITLE
java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by mthmulders** [stryker-mutator/stryker4s#574]
### Summary

Often - but not always - I'm seeing this in the Stryker4S log:

    04:09:27.238 [scala-execution-context-global-360] INFO  stryker4s.report.ConsoleReporter - Starting test-run 173...
    04:09:44.310 [scala-execution-context-global-360] INFO  stryker4s.run.TestRunner$$anon$2 - TestRunner crashed for mutant 172. Starting a new one and retrying this mutant 2 more time(s)
    [error] java.net.SocketException: Connection reset
    [error] 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
    [error] 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
    [error] 	at java.base/java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2824)
    [error] 	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2840)
    [error] 	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3337)
    [error] 	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:925)
    [error] 	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:368)
    [error] 	at stryker4s.sbt.runner.TestRunnerConnection$.$anonfun$create$4(TestRunnerConnection.scala:44)

I don't exactly understand what is happening here, and why I'm seeing this message. From the message, I don't know what to do either.

You can check the full logs in [GitHub actions](https://github.com/mthmulders/hyperion/runs/1110115036?check_suite_focus=true).

### Stryker4s config

```hocon
stryker4s {
  base-dir = "app"
  mutate = [
    "src/main/scala/**/*.scala"
  ]
  reporters = [
    console,
    dashboard
  ]
}
```

### Stryker4s environment

```
stryker4s 0.9.1+106-39ba27bd-SNAPSHOT
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        | 2.13.1 |
| Build tool & version | SBT 1.3.13 | 
| Operating System     | Ubuntu Linux |

**Comment by hugo-vrijswijk** [comment]
This always completely aborts the test-run? Could you try again with the latest 0.10.0-RC1 release? There were some improvements in the socket handling right before it I think. If its still happening in the RC release I'll investigate more

As for what's happening, it looks like the socket connection to the testrunner process has either crashed or already closed. This could be an error in the way the connection is handled (attempted reading after it is closed, though this is unlikely due to the setup). Or the main process 'thinks' the testrunner is still alive and starts sending messages to it, which fail because it is not alive. 

For the last case the testrunner should be restarted, but there could be something going wrong there. It's also possible that the previous mutant was a Timeout, which in your version doesn't restart the testrunner. In 0.10.0-RC1 it does, as it should.

**Comment by mthmulders** [comment]
> This always completely aborts the test-run? Could you try again with the latest 0.10.0-RC1 release? There were some improvements in the socket handling right before it I think. If its still happening in the RC release I'll investigate more

I don't think it _always_ does, but it _sometimes_ does, and I found the message to be rather unclear :-)

> For the last case the testrunner should be restarted, but there could be something going wrong there. It's also possible that the previous mutant was a Timeout, which in your version doesn't restart the testrunner. In 0.10.0-RC1 it does, as it should.

I've [bumped an upgrade](https://github.com/mthmulders/hyperion/commit/2f34f6af961e0976ef39976eababb221a560d7d3), let's see how it behaves overnight.

**Comment by mthmulders** [comment]
First run on GH Actions that actually succeeded, looks promising! Let's wait for one or two more runs and see if it's stable now.

**Comment by mthmulders** [comment]
It has run stable over the last couple of days. I think upgrading Stryker4S did the trick. Thanks for pointing that out!

**Comment by mthmulders** [comment]
I'm afraid I have to re-open. Should've waited one more night... Last night, [the run failed](https://github.com/mthmulders/hyperion/runs/1131948452?check_suite_focus=true), with the exact same error message:

    04:02:13.961 [scala-execution-context-global-357] INFO  stryker4s.run.TestRunner$$anon$2 - TestRunner crashed for mutant 209. Starting a new one and retrying this mutant 2 more time(s)
    04:02:15.433 [scala-execution-context-global-356] INFO  stryker4s.sbt.runner.ProcessTestRunner$ - Could not connect to testprocess. Retrying...
    04:02:18.048 [scala-execution-context-global-356] INFO  stryker4s.sbt.runner.ProcessTestRunner$ - Could not connect to testprocess. Retrying...
    04:02:29.242 [scala-execution-context-global-356] INFO  stryker4s.sbt.runner.ProcessTestRunner$ - Could not connect to testprocess. Retrying...
    04:02:37.837 [scala-execution-context-global-356] INFO  stryker4s.sbt.runner.ProcessTestRunner$ - Could not connect to testprocess. Retrying...
    04:02:42.964 [scala-execution-context-global-356] INFO  stryker4s.sbt.runner.ProcessTestRunner$ - Could not connect to testprocess. Retrying...
    [error] java.net.ConnectException: Connection refused (Connection refused)
    [error] 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
    [error] 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    [error] 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    [error] 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    [error] 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    [error] 	at java.base/java.net.Socket.connect(Socket.java:609)
    [error] 	at java.base/java.net.Socket.connect(Socket.java:558)
    [error] 	at java.base/java.net.Socket.<init>(Socket.java:454)
    [error] 	at java.base/java.net.Socket.<init>(Socket.java:264)
    [error] 	at stryker4s.sbt.runner.ProcessTestRunner$.$anonfun$connectToProcess$5(ProcessTestRunner.scala:91)
    [error] 	at map @ fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:370)
    [error] 	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:475)
    [error] 	at flatMap @ fs2.internal.CompileScope.$anonfun$open$2(CompileScope.scala:125)
    [error] 	at flatMap @ fs2.internal.CompileScope.open(CompileScope.scala:120)
    [error] 	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$13(Algebra.scala:505)
    [error] 	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$12(Algebra.scala:503)
    [error] 	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:414)
    [error] 	at flatMap @ fs2.internal.CompileScope.$anonfun$openAncestor$2(CompileScope.scala:231)
    [error] 	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$15(Algebra.scala:517)
    [error] 	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:216)
    [error] 	at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:215)
    [error] 	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:191)
    [error] 	at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:214)
    [error] 	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:191)
    [error] 	at flatMap @ fs2.internal.CompileScope.$anonfun$close$2(CompileScope.scala:212)
    [error] 	at flatMap @ fs2.internal.CompileScope.close(CompileScope.scala:211)
    [error] (stryker) java.net.ConnectException: Connection refused (Connection refused)

**Comment by hugo-vrijswijk** [comment]
Oh no! I'll investigate  (hopefully) this weekend

**Comment by hugo-vrijswijk** [comment]
@mthmulders Looking into the logs, I can see the test duration increasing with each run after a while before stopping altogether. That makes me think there is still some sort of memory leak, or resources not being cleaned up. My suspicion is that the resource buildup is so big after a while, that killing the process takes too long and a new testrunner can't start up. 

I've just published `0.10.0-RC2`. The testrunner process logic is cleaned up a little, but the biggest change is it now properly supports timeouts. So a timeout should occur before that even happens (and it will be reported as timeout). If you don't want timeouts reported, setting the new option `max-test-runner-reuse` to something like `50` should also be safe.

**Comment by mthmulders** [comment]
[Let's see what happens in the coming days](https://github.com/mthmulders/hyperion/commit/8362ee1f0f5da1da401c2762075265d8679ee253).

**Comment by hugo-vrijswijk** [comment]
Thanks for testing it out!

**Comment by mthmulders** [comment]
No success so far... :-\

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/430114/94006073-9171c080-fd9f-11ea-8d1f-41abaf4c504b.png">

https://github.com/mthmulders/hyperion/runs/1154538039

**Comment by hugo-vrijswijk** [comment]
![patience](https://media1.tenor.com/images/9077eb9a6ae44ab09f9fc1c3b9acb221/tenor.gif)

Looks like the release is still syncing to Maven Central

**Comment by mthmulders** [comment]
Now it's ✅ .

**Comment by mthmulders** [comment]
[Strange things happening are...](https://github.com/mthmulders/hyperion/runs/1164345430?check_suite_focus=true) Especially since the "main" workflow (that doesn't perform mutation testing) has all tests passing.

>  Error:  stryker4s.extension.exception.InitialTestRunFailedException: Initial test run failed. Please make sure your tests pass before running Stryker4s.
Error:  (stryker) stryker4s.extension.exception.InitialTestRunFailedException: Initial test run failed. Please make sure your tests pass before running Stryker4s.
Error:  Total time: 47 s, completed Sep 25, 2020, 6:20:52 AM
Error: Process completed with exit code 1.

**Comment by mthmulders** [comment]
Never mind the previous comment - it was 💯 my mistake.

Tonight Stryker4S failed again, this time it's not the initial test run but number 187. It says Connection Refused: https://github.com/mthmulders/hyperion/runs/1168968118?check_suite_focus=true

**Comment by hugo-vrijswijk** [comment]
@mthmulders Are you still running in to this issue with `0.10.0-RC3`?

**Comment by mthmulders** [comment]
I'm now [on 0.10.0-RC2](https://github.com/mthmulders/hyperion/blob/master/project/plugins.sbt#L10), and the [dashboard](https://dashboard.stryker-mutator.io/reports/github.com/mthmulders/hyperion/master) is updated nightly. Haven't tried with 0.10.0-RC3 recently, somehow ScalaSteward didn't offer a pull request just yet ;-)

**Comment by hugo-vrijswijk** [comment]
Something might be going wrong there, RC3 has been out for a while

**Comment by mthmulders** [comment]
[Let's see what it does](https://github.com/mthmulders/hyperion/pull/114)

**Comment by mthmulders** [comment]
Well, this night, Stryker4S ran significantly faster than it used to do (~8 mins vs. ~20 mins average over the last 10 successful runs).

It also calculated a significantly better score (96,8% vs 80,82%). That's very kind since I didn't change my code or my tests in between...

For reference, the previous run detected these mutants:

```
139. [Survived] [MethodExpression]
src/main/scala/hyperion/CollectingActor.scala:52:49
-	lineBuffer.indexOf(last)
+	lineBuffer.lastIndexOf(last)

150. [Survived] [EqualityOperator]
src/main/scala/hyperion/database/MeterReadingDAO.scala:45:51
-	===
+	=!=

152. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/Protocol.scala:8:19
-	"0001"
+	""

38. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:28:44
-	"/"
+	""

4. [Survived] [StringLiteral]
src/main/scala/hyperion/MeterAgent.scala:43:16
-	"Serial port operator closed normally"
+	""

42. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:34:45
-	"1-3:0.2.8("
+	""

45. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:35:45
-	"0-0:1.0.0("
+	""

47. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:35:84
-	"""[SW]\)"""
+	""

49. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:36:63
-	"""\w*"""
+	""

51. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:42:46
-	"0-0:96.14.0("
+	""

53. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:42:85
-	")"
+	""

56. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:44:46
-	"1-0:1.8.2("
+	""

58. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:45:46
-	"1-0:2.8.1("
+	""

59. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:45:81
-	"*kWh)"
+	""

61. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:46:81
-	"*kWh)"
+	""

62. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:47:46
-	"1-0:1.7.0("
+	""

63. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:47:81
-	"*kW)"
+	""

70. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:51:89
-	"""\w{0,96}"""
+	""

72. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:52:61
-	"""0-[1-4]:24.2.1\("""
+	""

73. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:52:89
-	"""\d{12}"""
+	""

76. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:53:110
-	"*m3)"
+	""

78. [Survived] [StringLiteral]
src/main/scala/hyperion/p1/P1TelegramParser.scala:54:89
-	"""\d{1}"""
+	""

03:56:33.160 [scala-execution-context-global-86] INFO  stryker4s.report.ConsoleReporter - Mutation score: 80.82%
```

While the latest run detected only these:
```
 [info] 10. [Survived] [StringLiteral]
[info] src/main/scala/hyperion/p1/P1TelegramParser.scala:28:44
[info] -	"/"
[info] +	""
[info] 
[info] 13. [Survived] [StringLiteral]
[info] src/main/scala/hyperion/p1/P1TelegramParser.scala:29:51
[info] -	".*"
[info] +	""
[info] 
[info] 15. [Survived] [StringLiteral]
[info] src/main/scala/hyperion/p1/P1TelegramParser.scala:34:63
[info] -	"""\d*"""
[info] +	""
[info] 
[info] 185. [Survived] [StringLiteral]
[info] src/main/scala/hyperion/core.scala:67:107
[info] -	"daily-history"
[info] +	""
[info] 
[info] 2. [Survived] [StringLiteral]
[info] src/main/scala/hyperion/RecentHistoryActor.scala:45:17
[info] -	"Sleeping for {}, system has {} records buffered"
[info] +	""
[info] 
[info] 21. [Survived] [StringLiteral]
[info] src/main/scala/hyperion/p1/P1TelegramParser.scala:36:63
[info] -	"""\w*"""
[info] +	""
[info] 
[info] 27. [Survived] [StringLiteral]
[info] src/main/scala/hyperion/p1/P1TelegramParser.scala:43:81
[info] -	"*kWh)"
[info] +	""
[info] Mutation score: 96.8%
```

**Comment by hugo-vrijswijk** [comment]
Are those newly killed mutants valid?

**Comment by mthmulders** [comment]
I did a sample with number 139 and 152 that were reported earlier. If I remove them and run my tests again, the tests are green. I would say they are not killed by a test. Will upgrade to 0.10.0 and see if they are still not reported. If they are not, I think it might be best to open a new issue, right?

**Comment by mthmulders** [comment]
It seems that the [last run](https://github.com/mthmulders/hyperion/runs/1581454728?check_suite_focus=true) (with Stryker 0.10) re-introduced those mutants. Let's close this case for now...
