### ISSUE TITLE
Static mutants always incorrectly marked as undetected

### ISSUE THREAD

**Issue by cbrunnkvist** [stryker-mutator/stryker4s#593]
### Summary

In the simplest of projects, a (string)mutation becomes reported as undetected despite clearly being covered by the test.

How to reproduce:
```bash
sbt new scala/scala-seed.g8 --name=stryker4s-undetected
cd stryker4s-undetected
echo 'addSbtPlugin("io.stryker-mutator" % "sbt-stryker4s" % "0.10.0-RC1")' >> project/plugins.sbt
sbt stryker
# FAILS - "hello" -> "" reported as undetected
echo 'addSbtPlugin("io.stryker-mutator" % "sbt-stryker4s" % "0.9.2")' > project/plugins.sbt
sbt stryker
# SUCCEEDS - "hello" -> "" is correctly reported as killed
```

### Stryker4s config

(none - simply relying on [the defaults](https://github.com/stryker-mutator/stryker4s/blob/master/docs/CONFIGURATION.md#mutate))

### Stryker4s environment

The bug must have been introduced somewhere **after v0.9.2** since it works correctly there.

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        |      `Scala 2.13.3`      |
| Build tool & version |      `SBT 1.3.13`      | 
| Operating System     |      `macOS 10.15.6`      |

**Comment by hugo-vrijswijk** [comment]
Hi! Unfortunately this is a limitation of the new testrunner. It reuses a running Java process. Which means that any singleton values (like a `val` in an `object`) are instantiated only once and can not be dynamically set to its mutations. If you change the `val` in the trait to a `def` or create a new instantiation of the trait outside of the object in the test you should see the mutation showing up as killed correctly. 

I've written an idea for a possible solution here: https://github.com/stryker-mutator/stryker4s/pull/565#issuecomment-688438699 which I want before the full `0.10.0` release. Note that this solution means the mutant will show up as ignored, and not 'properly' test the mutant. If you want that you could use the `legacy-test-runner` config option

**Comment by cbrunnkvist** [comment]
Thanks for the explanation. I notice that `max-test-runner-reuse: 0` makes no difference, but `legacy-test-runner: true` works as a workaround in `0.10.0-RC2`.
