### ISSUE TITLE
Rethink logging

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#620]
## ❓ The situation

Right now Stryker4s uses [grizzled-slf4j](https://github.com/bmc/grizzled-slf4j) for logging. grizzled-slf4j uses [slf4j](http://www.slf4j.org/) underneath which requires an underlying logging implementation, we use [log4j](https://logging.apache.org/log4j/2.x/). Grizzled-slf4j is easy to work with because you just need to mix in a trait and you have logging functions available.

## ⚠ The problem

This setup has a couple of problems for Stryker4s:

1. It's complex. We need 3 different frameworks just to output some text to a terminal. Surely we can do better
2. Doesn't work well on all plugins. Log4j works well with maven, but sbt has it's own log-manager they expect you to use. They've also recently [gotten rid of the log4j dependency](https://github.com/sbt/sbt/pull/5731) in sbt 1.4 which has now broken logging for Stryker4s (see also point 1)
3. Difficult to test. Yes, we should test logging 😉. Logging right now is a side-effectful function. We've had to create complex [TestAppenders](https://github.com/stryker-mutator/stryker4s/blob/master/core/src/test/scala/stryker4s/testutil/TestAppender.scala) with custom [log4j config](https://github.com/stryker-mutator/stryker4s/blob/master/core/src/test/resources/log4j2-test.xml) just to capture logged events. This also doesn't work well with parallel tests because all log events are appended to the same list. From a FP point-of-view, the side-effectful `Unit` functions also don't play well.
4. Log4j is java-only. Should we ever want/need to cross-compile to Scala.js this will cause issues.

## ✔ The (possible) solutions

I think we should get rid of grizzled-slf4j and any slf4j/log4j references in `stryker4s-core` and replace it with a different logging framework. There are some requirements:

- No dependency on any Java-based logging frameworks. See points above
- Easy to test. This probably means we need to inject a logging instance into classes instead of mixing in a trait like we do now. Probably a lot of refactoring required
- Ability to swap logging 'backend' implementations. Sbt should use it's logmanager, Maven and command-runner should use log4j, etcetera
- Ability to set log-level programmatically. Not needed for sbt, (or maven, if we use log4j). But the command-runner does need a way to set the log-level

Considering this I think there are a few options:

|                                                                   | Testability  | Custom frameworks | Set log-level | No Log4j/slf4j needed                | Notes                                                                                                                 |
| ----------------------------------------------------------------- | ------------ | ----------------- | ------------- | ------------------------------------ | --------------------------------------------------------------------------------------------------------------------- |
| [Log4cats](https://christopherdavenport.github.io/log4cats/)      | ✅           | ✅                | ✅            | ✅                                   | Logging returns a `F[Unit]`, more refactoring needed but works well with FP-code that is being integrated more lately |
| Custom logging class                                              | ✅           | ✅                | ✅            | ✅                                   | More work needed to integrate with sbt, log4j (maven), etc                                                            |
| [Scribe](https://github.com/outr/scribe)                          | ❓ Probably? | ✅                | ✅            | ✅                                   |                                                                                                                       |
| [Airframe-log](https://wvlet.org/airframe/docs/airframe-log.html) | ❌           | ✅                | ✅            | ❌ (uses `java.util.logging` though) |                                                                                                                       |
| [Blindsight](https://tersesystems.github.io/blindsight/)          | ❌           | ✅                | ✅            | ❌                                   |                                                                                                                       |
| [Log4s](https://github.com/Log4s/log4s)                           | ❌           | ✅                | ✅            | ❌                                   |                                                                                                                       |
| [Scala-logging](https://github.com/lightbend/scala-logging)       | ❌           | ✅                | ✅            | ❌                                   |                                                                                                                       |

**Comment by nicojs** [comment]
IMO: Go with your own logging implementation. Make it simple and sweet. Maximum flexibility 🤷‍♂️. Call it hulog.
