### ISSUE TITLE
Config option to not delete temp dir after running

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker4s#668]
Right now the temp dir is deleted after running using a FS2 tempDir [`Resource`](https://typelevel.org/cats-effect/docs/std/resource). This is done in the [MutantRunner](https://github.com/stryker-mutator/stryker4s/blob/master/core/src/main/scala/stryker4s/run/MutantRunner.scala#L53). 
It'd be nice to have a config option to keep the generated temp dir after running for debugging purposes to look at the generated code. An option similar to [Strykers](https://stryker-mutator.io/docs/stryker/configuration#cleantempdir-boolean) would be preferred.

Instead of `Files[IO].tempDirectory()` which returns a resource that removes the directory when closed, we can use `Files[IO].createTempDirectory` when the config option is enabled which only creates, but not removes

**Comment by cbrunnkvist** [comment]
Yeah that would probably be useful, not in normal use but debugging. Perhaps a `stryker4s.skip-cleanup` or `stryker4s.debug.skip-cleanup` config boolean..?

**Comment by hugo-vrijswijk** [comment]
I think it's good to keep in line with Stryker-js, which uses [`cleanTempDir`](https://stryker-mutator.io/docs/stryker-js/configuration/#cleantempdir-boolean), so the Stryker4s option would be `clean-temp-dir`

**Comment by hugo-vrijswijk** [comment]
Fixed in #1263
