### ISSUE TITLE
Tagging log tests

### ISSUE THREAD

**Issue by legopiraat** [stryker-mutator/stryker4s#73]
### Summary

The logging tests are pretty unstable and randomly crash a lot. We could tag them using `Scalatest` and only run them `locally` or once in a while to get the build a bit more stable.

ref. http://www.scalatest.org/user_guide/tagging_your_tests 

What do you think @hugo-vrijswijk should we implement this or not?

**Comment by hugo-vrijswijk** [comment]
Hmm, I'm not a huge fan of only running certain tests locally instead of on the build server. Would make it pretty difficult with PR's. I'd be interested in what the exact cause of the unstable tests are

**Comment by legopiraat** [comment]
Oke lets not do this, closing this issue
