### ISSUE TITLE
"Failed to add mutation" report

### ISSUE THREAD

**Issue by nrinaudo** [stryker-mutator/stryker4s#776]
### Summary

I have been asked by stryker4s to fill in a but report while toying with it for scalacheck:

```
[warn] Failed to add mutation(s) 690, 691, 692 to new mutated code
[warn] The code that failed to mutate was: [try{
[warn]     val (p1, s, rs1) = runSeqCmds(sut, as.s, as.seqCmds)
[warn]     val l1 = s"Initial State:\n  ${as.s}\nSequential Commands:\n${prettyCmdsRes(as.seqCmds zip rs1, maxLength)}"
[warn]     if(as.parCmds.isEmpty) p1 :| l1
[warn]     else propAnd(p1.flatMap{r => if(!r.success) finalize; Prop(prms => r)} :| l1, {
[warn]       try{
[warn]       val (p2, rs2) = runParCmds(sut, s, as.parCmds)
[warn]       val l2 = rs2.map(prettyCmdsRes(_, maxLength)).mkString("\n\n")
[warn]       p2 :| l1 :| s"Parallel Commands (starting in state = ${s})\n$l2"
[warn]       }
[warn]       finally finalize
[warn]     })
[warn]     }
[warn]     finally if(as.parCmds.isEmpty) finalize] at Input.File(new File("/path/to/scalacheck/src/main/scala/org/scalacheck/commands/Commands.scala"), Charset.forName("UTF-8")):351:5
[warn] This mutation will likely show up as Survived
[warn] Please open an issue on github with sample code of the mutation that failed: https://github.com/stryker-mutator/stryker4s/issues/new
```

Note that the stryker4s SBT command took over 10 minutes before it started running any test, which I feel is a bit long, or at least not at all what the ScalaLove talk led me to expect. Maybe there's an underlying issue on my system?

### Stryker4s config

```hocon
stryker4s {
  scala-dialect: "2.12"
}
```

### Stryker4s environment

```
stryker4s 0.11.0
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        |    2.12.13        |
| Build tool & version |  SBT 1.4.9          | 
| Operating System     |   Linux (Ubuntu)         |

**Comment by hugo-vrijswijk** [comment]
Hi @nrinaudo, sorry for not getting back to you sooner 🙈. I've just fixed the bug above, and I'm hoping to release it in `v0.12.0` sometime within the next week. 

It's unfortunate to hear that starting took so long when running Stryker4s on ScalaCheck. Before running your tests, Stryker4s does 2 things: parse and mutate files & compile the mutants in those files. The second step shouldn't take much longer than a normal clean compile. For the first one, I think I've noticed before that on large files (>1000 LoC), Stryker4s will take exponentially long to parse and mutate those files. Big files are not unexpected in a large project like ScalaCheck, and this is definitely something that Stryker4s should be able to handle properly! 

I've created https://github.com/stryker-mutator/stryker4s/issues/850 to keep track of it, though I don't think it's something I'll be able to get to very soon.
