### ISSUE TITLE
Document versioning strategy

### ISSUE THREAD

**Issue by legopiraat** [stryker-mutator/stryker4s#86]
### Summary

To be able to have clear versioning for Stryker4s we need to define and document a strategy.

**Do we want to publish multiple artifacts on the same version?**

1. Publish the same version for all artifacts.
    For example the sbt plugin + the stryker api both on the same version.
    Libraries like Akka are doing this strategy. 
2. Publish each artifact on a different version.
    Current Stryker is doing this. Gives us more flexibility but also more complexity.

**Comment by hugo-vrijswijk** [comment]
Downside to option 1: New releases might not actually have any changes (update to core, for example, even though only sbt-plugin has changed). Does this really matter?

Downside to option 2: More complex, I think having automated release generation really is necessary for this

**Comment by legopiraat** [comment]
Upside for option 1: 
Backward compatibility testing is easier to maintain (basically because there is none needed).

**Comment by scelestino** [comment]
Upside for option 1 too.

I think that the main artifact for a project that use stryker is the plugin, but the lifecycling of core would be more changing, so every time we release core, we need to release the plugin. Would be easy for how use stryker.

**Comment by legopiraat** [comment]
That is a very good point, was also thinking along those lines as well.

**Comment by legopiraat** [comment]
@hugo-vrijswijk You oke if we take option 1? Since our main goal would be plugins to run stryker4s one common version would save us a lot of troubles.
