### ISSUE TITLE
Uncompilable code after mutating inline XML literals?

### ISSUE THREAD

**Issue by cbrunnkvist** [stryker-mutator/stryker4s#928]
### Summary

I have code that makes use of [NodeSeq, Elem](https://alvinalexander.com/scala/scala-xml-examples-xml-literals-source-code-searching-xpath/) and other classes and methods from the `scala.xml._` section of the standard library, with lots of inline XML-snippets.

These files seem to mutate fine, but from what I can tell, produces non-compilable Scala. Errors like below:
```
[error] (Compile / compileIncremental) Compilation failed
[error] stryker4s.extension.exception.TestSetupException: Could not setup mutation testing environment. Unable to resolve project classpath. This could be due to compile errors or misconfiguration of Stryker4s. See debug logs for more information.
[error] 	at stryker4s.sbt.Stryker4sSbtRunner.extractTaskValue$1(Stryker4sSbtRunner.scala:77)
[error] 	at stryker4s.sbt.Stryker4sSbtRunner.setupSbtTestRunner$1(Stryker4sSbtRunner.scala:81)
[error] 	at stryker4s.sbt.Stryker4sSbtRunner.resolveTestRunners(Stryker4sSbtRunner.scala:150)
```

Is this a known shortcoming or something that can be easily fixed?

**Comment by hugo-vrijswijk** [comment]
The issue is xml literals are parsed in the AST as Lit.Strings. I'm making a fix to exclude them (but anything interpolated inside the xml literal will still be mutated)
