### ISSUE TITLE
Getting StackOverflow traversing the Tree

### ISSUE THREAD

**Issue by scelestino** [stryker-mutator/stryker4s#93]
### Summary

I tested Stryker with a couple of real projects, and I have the same issue with both of them.

> [error] java.lang.StackOverflowError
[error]         at scala.meta.transversers.Transformer.apply(Transformer.scala:4)
[error]         at stryker4s.extensions.TreeExtensions$ImplicitTreeExtensions$OnceTransformer.super$apply(TreeExtensions.scala:81)
[error]         at stryker4s.extensions.TreeExtensions$ImplicitTreeExtensions$OnceTransformer.$anonfun$apply$1(TreeExtensions.scala:81)
[error]         at scala.Option.getOrElse(Option.scala:121)
[error]         at stryker4s.extensions.TreeExtensions$ImplicitTreeExtensions$OnceTransformer.apply(TreeExtensions.scala:81)
[error]         at scala.meta.transversers.Transformer.apply(Transformer.scala:4)
[error]         at stryker4s.extensions.TreeExtensions$ImplicitTreeExtensions$OnceTransformer.super$apply(TreeExtensions.scala:81)
[error]         at stryker4s.extensions.TreeExtensions$ImplicitTreeExtensions$OnceTransformer.$anonfun$apply$1(TreeExtensions.scala:81)
[error]         at scala.Option.getOrElse(Option.scala:121)

The main problem here is that `OnceTransformer.apply` is not tail recursive and it breaks with large files (that is, large trees). I'm going to give it a look.

### Stryker config

```
stryker4s {
  mutate: ["app/**/*.scala"],
  base-dir: "/home/scelestino/dev/myapp"
}
```

### Stryker4s environment

The SBT branch.

```
stryker4s 0.1.0-SNAPSHOT
```

### Your Environment

Scala 2.12.7
SBT 1.0.3
OS Ubuntu

**Comment by scelestino** [comment]
I found that is not related to scalameta, maybe a bug in stryker. I'll try to find it.

**Comment by scelestino** [comment]
Ok, I can reproduce this issue trying to mutate the following code.

```
  val map:Map[String, Int] = Map(
    "a" -> 1,
    "b" -> 1,
    "c" -> 1,
    "d" -> 1,
    "e" -> 1,
    "f" -> 1,
    "g" -> 1,
    "h" -> 1,
    "i" -> 1,
    "j" -> 1,
    "k" -> 1,
    "l" -> 1,
    "m" -> 1,
    "n" -> 1,
    "o" -> 1,
    "p" -> 1,
    "q" -> 1,
    "r" -> 1,
    "s" -> 1,
    "t" -> 1,
    "u" -> 1,
    "v" -> 1,
    "w" -> 1,
    "x" -> 1,
    "y" -> 1,
    "z" -> 1,
  )
```

The problem is that the generated code has a lot of boilerplate. My original file had 60 mutations, and it broke after 29.

If I take a simpler example like
```  
val map:Map[String, Int] = Map(
    "a" -> 1,
    "b" -> 1,
    "c" -> 1
)
```

the generated code is

``` 
val map: Map[String, Int] = sys.props.get("ACTIVE_MUTATION").orElse(sys.env.get("ACTIVE_MUTATION")) match {
    case Some("0") =>
      Map("" -> 1, "b" -> 1, "c" -> 1)
    case _ =>
      sys.props.get("ACTIVE_MUTATION").orElse(sys.env.get("ACTIVE_MUTATION")) match {
        case Some("1") =>
          Map("a" -> 1, "" -> 1, "c" -> 1)
        case _ =>
          sys.props.get("ACTIVE_MUTATION").orElse(sys.env.get("ACTIVE_MUTATION")) match {
            case Some("2") =>
              Map("a" -> 1, "b" -> 1, "" -> 1)
            case _ =>
              Map("a" -> 1, "b" -> 1, "c" -> 1)
          }
      }
  }
```

instead of
(50% smaller)

```
  val map: Map[String, Int] = Map(
    sys.props.get("ACTIVE_MUTATION").orElse(sys.env.get("ACTIVE_MUTATION")) match {
      case Some("0") => ""
      case _ => "a"
    } -> 1,
    sys.props.get("ACTIVE_MUTATION").orElse(sys.env.get("ACTIVE_MUTATION")) match {
      case Some("1") => ""
      case _ => "b"
    } -> 1,
    sys.props.get("ACTIVE_MUTATION").orElse(sys.env.get("ACTIVE_MUTATION")) match {
      case Some("2") => ""
      case _ => "c"
    } -> 1,
  )
```



I have two proposals

First, we need to change the way replace works, one expression (a String, a Boolean, a method call) should be replaced one by one with one expression of the same type (the match). The only place where is not possible to do that is on a case statement, but I think there is a way to fix that.

In this example, the String "a" is replaced by MUTATION match { .... } that returns an String, etc.


Secondly, we can change `sys.props.get("ACTIVE_MUTATION").orElse(sys.env.get("ACTIVE_MUTATION"))` for something like `Stryker.currentMutation` in order to decrease the output tree.


Another way to reduce the output tree is replacing all the match with a function call, like this
```
val map: Map[String, Int] = Map(
    Stryker.mutation("a", "0" -> "") -> 1,
    Stryker.mutation("b", "1" -> "") -> 1,
    Stryker.mutation("c", "2" -> "", "3" -> "anotherMutation") -> 1,
  )
```

If the tree become too big, it will break because Transform.apply is not tail recursive. Boilerplate doesn't help with that. 

There is no point to get nested matchs, there is only one mutation at once.

What do you thing?
@legopiraat @hugo-vrijswijk

**Comment by scelestino** [comment]
Now you mention large statements I remember that I had the same issue with a RequestBuilder with a lot of method calls.

The main problem with the generated code is that it grows exponentially with large statements, so the chance of get a StackOverflow is higher. A Map of 10 Strings mutate into ten Maps of 10 Strings (100 Strings), a Map of 20 Strings mutate into 400 Strings.

I agree with your solution, if `topStatement` stops at parameters it will work with statements like `List(...)`, `Map(...)` or code like `builer.setA("").setB("") ..... setX("").build()`.

**Comment by legopiraat** [comment]
I'll take this one
